DROP TABLE EPTD_CARGA_LOG
DROP TABLE EPTD_CARGA_BIT 
CREATE TABLE EPTD_CARGA_BIT (
  ID_CARGA NUMBER(10,0) NOT NULL,
  COD_CLIE NUMBER(10,0),
  COD_SEGM NUMBER(10,0),
  NOM_ARCHIVO VARCHAR2(200 BYTE) NOT NULL,
  NOM_ARCH_CLI VARCHAR2(200 BYTE) NOT NULL,
  EST_ENVIO VARCHAR2(2 BYTE),
  FEC_ENVIO DATE,
  TIP_ENVIO VARCHAR2(20 BYTE)
)  
TABLESPACE EPM_MSG_DATA ;
ALTER TABLE EPTD_CARGA_BIT ADD CONSTRAINT EPTD_CARGA_BIT_PK PRIMARY KEY (ID_CARGA);

CREATE TABLE EPTD_CARGA_LOG(
  ID_INT INTEGER,
  ID_CARGA NUMBER(10,0),
  NUM_LNEA INTEGER,
  MSG_ERROR VARCHAR(2000)
)TABLESPACE EPM_MSG_DATA ; 
ALTER TABLE EPTD_CARGA_LOG ADD CONSTRAINT EPTD_CARGA_LOG_PK PRIMARY KEY (ID_INT);
ALTER TABLE EPTD_CARGA_LOG ADD FOREIGN KEY (ID_CARGA) REFERENCES EPTD_CARGA_BIT(ID_CARGA);

CREATE SEQUENCE SEQ_EPTD_SEGM_SUJE_CLIE START WITH 106000 INCREMENT BY 1;
CREATE SEQUENCE SQ_EPMC_CLIE_SUJE_0001 START WITH 267000 INCREMENT BY 1;
CREATE SEQUENCE SQ_EPMC_SUJE_0001 START WITH 265000 INCREMENT BY 1;
CREATE SEQUENCE SQ_EPTD_CARGA_BIT_0001 INCREMENT BY 1 START WITH 1;

drop table EPTD_CLIE_SUJE_TIPO_SCOR;


--INSERT INTO EPTD_CARGA_BIT (ID_CARGA,COD_SEGM, COD_CLIE, NOM_ARCHIVO, NOM_ARCH_CLI,EST_ENVIO, FEC_ENVIO, TIP_ENVIO) VALUES (1,'12', '11', '/Users/indiegente/Documents/multiplica/ic/files/12-11-1428508989-2-.csv', 'D:/dev/projects/equifax-epm/pentaho/procesados/12-11-1428508989-2-.csv', 'E', TO_DATE('2015-03-31', 'YYYY-MM-DD'),'CLIENTE_SEGMENTO');


--SELECT * FROM EPTD_CARGA_BIT WHERE EST_ENVIO='E' ORDER BY FEC_ENVIO,COD_CLIE DESC

--ALTER TABLE EPTD_CARGA_BIT DROP CONSTRAINT C_EPTD_SUJESEG_001 
--UPDATE EPMC_SEGM SET COD_CLIE=11;
--select * from EPMC_SEGM
--SELECT * FROM EPMC_CLIE_SUJE A INNER JOIN EPMC_SUJE B ON A.COD_SUJE=B.COD_SUJE
--WHERE A.COD_CLIE=11
--select SQ_EPMC_SUJE_0001.nextval from dual
--
--SELECT MAX(COD_SUJE) FROM EPMC_SUJE