ALTER TABLE EPM_MSG.EPTD_ALER ADD DES_VALO VARCHAR(255);

UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Registro de Créditos Consolidados', DES_CART = 'Bancos y Financieras (SBS)' WHERE COD_ALER_PROD = 1;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Cuentas Corrientes Cerradas', DES_CART = 'Cuenta Corriente Cerrada' WHERE COD_ALER_PROD = 2;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Tarjetas de Crédito Anuladas', DES_CART = 'Tarjeta de Crédito Anulada' WHERE COD_ALER_PROD = 3;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Consolidado de Morosidad (SICOM)', DES_CART = 'Morosidad' WHERE COD_ALER_PROD = 4;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Indicador de Consultas', DES_CART = 'Consultas realizadas' WHERE COD_ALER_PROD = 5;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Negativo Sunat (NEGSUNAT)', DES_CART = 'Informe Negativo de Sunat' WHERE COD_ALER_PROD = 6;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Protesto', DES_CART = 'Documento Protestado' WHERE COD_ALER_PROD = 7;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Deuda de Microfinanzas (DECOMICRO)', DES_CART = 'Deudas en Microfinanzas' WHERE COD_ALER_PROD = 8;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Rating de EPM', DES_CART = 'Categoria de Riesgo' WHERE COD_ALER_PROD = 9;
UPDATE EPM_MSG.EPMC_ALER_PROD SET DES_INFO_PROD_MAIN = 'Score Lite', DES_CART = 'Score de Equifax Lite' WHERE COD_ALER_PROD = 10;

-----------------------------------------------------------------------------------------------------------------------------------------------------------

UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'AUMENTE', DES_TABL_CORR_AGRUP = 'han aumentado', DES_TABL_CORR_INDI = 'Ha aumentado' WHERE COD_OPCI_CONF = 1;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'DISMINUYA', DES_TABL_CORR_AGRUP = 'han disminuido', DES_TABL_CORR_INDI = 'Ha disminuido' WHERE COD_OPCI_CONF = 2;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'MEJORE', DES_TABL_CORR_AGRUP = 'han mejorado', DES_TABL_CORR_INDI = 'Ha mejorado' WHERE COD_OPCI_CONF = 3;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'EMPEORE', DES_TABL_CORR_AGRUP = 'han empeorado', DES_TABL_CORR_INDI = 'Ha empeorado' WHERE COD_OPCI_CONF = 4;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'CAMBIE', DES_TABL_CORR_AGRUP = 'han cambiado', DES_TABL_CORR_INDI = 'Ha cambiado' WHERE COD_OPCI_CONF = 5;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'EXISTA', DES_TABL_CORR_AGRUP = 'tienen',DES_TABL_CORR_INDI =  'Tiene' WHERE COD_OPCI_CONF = 6;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'COMERCIAL', DES_TABL_CORR_AGRUP = 'Entidades Comerciales', DES_TABL_CORR_INDI = 'Entidades Comerciales' WHERE COD_OPCI_CONF = 7;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'FINANCIERO Y SEGUROS', DES_TABL_CORR_AGRUP = 'Entidades Financieras', DES_TABL_CORR_INDI = 'Entidades Financieras' WHERE COD_OPCI_CONF = 8;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'INDUSTRIAL', DES_TABL_CORR_AGRUP = 'Entidades Industriales', DES_TABL_CORR_INDI = 'Entidades Industriales' WHERE COD_OPCI_CONF = 9;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'MICRO FINANZAS NO SUPERVISADAS', DES_TABL_CORR_AGRUP = 'Entidades de Microfinanzas', DES_TABL_CORR_INDI = 'Entidades de Microfinanzas' WHERE COD_OPCI_CONF = 10;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'MICRO FINANZAS SUPERVISADAS', DES_TABL_CORR_AGRUP = 'Entidades de Microfinanzas', DES_TABL_CORR_INDI = 'Entidades de Microfinanzas' WHERE COD_OPCI_CONF = 11;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'OTROS SECTORES', DES_TABL_CORR_AGRUP = 'Otros tipos de entidades', DES_TABL_CORR_INDI = 'Otros tipos de entidades' WHERE COD_OPCI_CONF = 12;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'SERVICIOS ENERGETICOS', DES_TABL_CORR_AGRUP = 'Entidades de Servicio Energéticos', DES_TABL_CORR_INDI = 'Entidades de Servicio Energéticos' WHERE COD_OPCI_CONF = 13;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'SERVICIOS', DES_TABL_CORR_AGRUP = 'Entidades de Servicios', DES_TABL_CORR_INDI = 'Entidades de Servicios' WHERE COD_OPCI_CONF = 14;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'TELECOMUNICACIONES', DES_TABL_CORR_AGRUP = 'Entidades de Telecomunicaciones', DES_TABL_CORR_INDI = 'Entidades de Telecomunicaciones' WHERE COD_OPCI_CONF = 15;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'TRANSPORTE Y CARGA', DES_TABL_CORR_AGRUP = 'Entidades de Transporte', DES_TABL_CORR_INDI = 'Entidades de Transporte' WHERE COD_OPCI_CONF = 16;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'PORCENTUAL', DES_TABL_CORR_AGRUP = '', DES_TABL_CORR_INDI = '' WHERE COD_OPCI_CONF = 17;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'CANTIDAD', DES_TABL_CORR_AGRUP = '', DES_TABL_CORR_INDI = '' WHERE COD_OPCI_CONF = 18;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'ORDEN', DES_TABL_CORR_AGRUP = '', DES_TABL_CORR_INDI = '' WHERE COD_OPCI_CONF = 19;
UPDATE EPM_MSG.EPMC_OPCI_CONF SET DES_IDEN_TABL = 'EXISTENCIA', DES_TABL_CORR_AGRUP = '', DES_TABL_CORR_INDI = '' WHERE COD_OPCI_CONF = 20;

---DELETE
DELETE FROM EPTD_ALER;
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(61,82955,'20513854383','2',TO_DATE('04/07/2015','MM/dd/yyyy'),1,5,'su deuda castigada en 10 ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(63,82956,'20101206247','2',TO_DATE('04/07/2015','MM/dd/yyyy'),1,2,'la deuda vigente en 20 ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(65,82957,'10672666','1',TO_DATE('04/07/2015','MM/dd/yyyy'),1,1,'la calificación en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(67,82958,'20101206247','2',TO_DATE('04/07/2015','MM/dd/yyyy'),1,1,'la calificación en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(69,82959,'10672666','1',TO_DATE('04/07/2015','MM/dd/yyyy'),1,2,'su saldo en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(71,82960,'20101206247','2',TO_DATE('04/07/2015','MM/dd/yyyy'),1,1,'su saldo en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(73,82961,'20520696378','1',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(75,82962,'20505465190','1',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(77,82963,'20522138356','1',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(79,82964,'20519084571','2',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(81,82965,'20513854383','2',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(83,82966,'20101392954','2',TO_DATE('04/07/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(21,82967,'20513854383','2',TO_DATE('03/30/2015','MM/dd/yyyy'),1,5,'su deuda castigada en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(23,82968,'20101206247','2',TO_DATE('03/30/2015','MM/dd/yyyy'),1,2,'la deuda vigente en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(25,82969,'10672666','1',TO_DATE('03/30/2015','MM/dd/yyyy'),1,1,'la calificación en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(27,82970,'20101206247','2',TO_DATE('03/30/2015','MM/dd/yyyy'),1,1,'la calificación en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(29,82971,'10672666','1',TO_DATE('03/30/2015','MM/dd/yyyy'),1,2,'su saldo en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(31,82972,'20101206247','2',TO_DATE('03/30/2015','MM/dd/yyyy'),1,1,'su saldo en ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(33,82973,'20520696378','1',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(35,82974,'20505465190','1',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(37,82975,'20522138356','1',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(39,82976,'20519084571','2',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(41,82977,'20513854383','2',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
INSERT INTO EPTD_ALER(COD_ALER, COD_SUJE, TXT_NUME_DOCU, TXT_TIPO_DOCU, FEC_FECH_REGI, COD_ALER_PROD, COD_OPCI_CONF, DES_VALO) VALUES(43,82978,'20101392954','2',TO_DATE('03/30/2015','MM/dd/yyyy'),7,2,'el importe de un ');
